<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { NButton, NFormItem, NInput, NInputNumber, NModal, NSelect, NSpin, NSwitch, useDialog, useMessage } from 'naive-ui'
import { IconAutomation, IconPlus, IconSparkles, IconTrash } from '@tabler/icons-vue'
import { api } from '../api'
import type { AiCompileResult, AutomationRule, Paged } from '../types'
import PageHeader from '../components/PageHeader.vue'
import { formatDate } from '../format'
import PaginationBar from '../components/PaginationBar.vue'

const message=useMessage();const dialog=useDialog();const loading=ref(true);const saving=ref(false);const showEditor=ref(false);const step=ref(1);const editingId=ref<number|null>(null);const page=ref(1);const pageSize=ref(20);const rules=ref<Paged<AutomationRule>>({items:[],total:0,page:1,pageSize:20,totalPages:0})
const form=reactive({name:'',enabled:true,triggerType:'NEW_RESOURCE',cron:'',providerKey:'',keyword:'',minScore:70,requireSubtitle:false,actionType:'ACQUIRE',mode:'CONFIRM' as AutomationRule['mode']})
const triggers=[{label:'发现新资源',value:'NEW_RESOURCE'},{label:'已关注演员出现新资源',value:'FOLLOWED_ACTOR_UPDATE'},{label:'定时检查资源',value:'SCHEDULE'}]
const modes=[{label:'确认后获取',value:'CONFIRM'},{label:'自动获取',value:'AUTO'},{label:'仅通知',value:'NOTIFY'}]
const aiPrompt=ref('')
const aiBusy=ref(false)
const aiResult=ref<AiCompileResult|null>(null)
const creatingFromAi=ref(false)
async function load(){try{rules.value=await api.automations(page.value,pageSize.value)}catch(reason){message.error(reason instanceof Error?reason.message:'自动化加载失败')}finally{loading.value=false}}
function changePage(value:number){page.value=value;load()}
function changePageSize(value:number){pageSize.value=value;page.value=1;load()}
function open(rule?:AutomationRule){editingId.value=rule?.id??null;step.value=1;Object.assign(form,{name:rule?.name??'',enabled:rule?.enabled??true,triggerType:rule?.triggerType??'NEW_RESOURCE',cron:String(rule?.triggerConfig?.cron??''),providerKey:String(rule?.conditions?.providerKey??''),keyword:String(rule?.conditions?.keyword??''),minScore:Number(rule?.conditions?.minScore??70),requireSubtitle:Boolean(rule?.conditions?.requireSubtitle??false),actionType:rule?.actionType??'ACQUIRE',mode:rule?.mode??'CONFIRM'});showEditor.value=true}
async function save(){if(!form.name.trim()){message.warning('请填写规则名称');return}if(form.triggerType==='SCHEDULE'&&!form.cron.trim()){message.warning('请填写 cron 表达式，例如 0 20 * * 1');return}saving.value=true;const input={name:form.name,enabled:form.enabled,triggerType:form.triggerType,triggerConfig:form.triggerType==='SCHEDULE'?{cron:form.cron.trim()}:{},conditions:{providerKey:form.providerKey,keyword:form.keyword,minScore:form.minScore,requireSubtitle:form.requireSubtitle},actionType:form.actionType,actionConfig:{},mode:form.mode};try{if(editingId.value)await api.updateAutomation(editingId.value,input);else await api.createAutomation(input);message.success('自动化规则已保存');showEditor.value=false;await load()}catch(reason){message.error(reason instanceof Error?reason.message:'保存失败')}finally{saving.value=false}}
async function toggle(rule:AutomationRule,value:boolean){try{rule.enabled=(await api.setAutomationEnabled(rule.id,value)).enabled}catch(reason){message.error(reason instanceof Error?reason.message:'更新失败')}}
function remove(rule:AutomationRule){dialog.warning({title:'删除自动化规则',content:`确认删除“${rule.name}”吗？历史执行记录会一并删除。`,positiveText:'删除',negativeText:'返回',onPositiveClick:async()=>{try{await api.deleteAutomation(rule.id);message.success('规则已删除');await load()}catch(reason){message.error(reason instanceof Error?reason.message:'删除失败')}}})}
async function generate(){if(!aiPrompt.value.trim()){message.warning('请先描述你的需求');return}aiBusy.value=true;aiResult.value=null;try{aiResult.value=await api.compileAi(aiPrompt.value.trim())}catch(reason){message.error(reason instanceof Error?reason.message:'生成失败')}finally{aiBusy.value=false}}
async function createFromAi(){const rule=aiResult.value?.rule;if(!rule)return;creatingFromAi.value=true;try{await api.createAutomation(rule);message.success('AI 规则已创建');aiResult.value=null;aiPrompt.value='';await load()}catch(reason){message.error(reason instanceof Error?reason.message:'创建失败')}finally{creatingFromAi.value=false}}
function openFromAi(){const rule=aiResult.value?.rule;if(!rule)return;editingId.value=null;step.value=1;Object.assign(form,{name:rule.name??'',enabled:rule.enabled??true,triggerType:rule.triggerType??'NEW_RESOURCE',cron:String(rule.triggerConfig?.cron??''),providerKey:String(rule.conditions?.providerKey??''),keyword:String(rule.conditions?.keyword??''),minScore:Number(rule.conditions?.minScore??70),requireSubtitle:Boolean(rule.conditions?.requireSubtitle??false),actionType:rule.actionType??'ACQUIRE',mode:rule.mode??'CONFIRM'});showEditor.value=true}
onMounted(load)
</script>
<template><PageHeader title="自动化" description="用自然语言描述需求，或手动配置 WHEN / IF / THEN 规则。所有获取仍进入同一个可审计流程。"><n-button type="primary" @click="open()"><template #icon><IconPlus /></template>新建规则</n-button></PageHeader>
<section class="ai-assistant"><div class="ai-assistant-head"><span class="ai-icon"><IconSparkles :size="18" /></span><div><strong>AI 助手</strong><small>用一句话描述需求，自动生成定时或监听规则，确认后才会生效</small></div></div><div class="ai-assistant-input"><n-input v-model:value="aiPrompt" type="textarea" :autosize="{ minRows: 2, maxRows: 4 }" placeholder="例如：每周一晚上 8 点，自动下载 ABC 开头、有中文字幕、评分 80 以上的新片" /><n-button type="primary" :loading="aiBusy" @click="generate"><template #icon><IconSparkles /></template>生成规则</n-button></div><div v-if="aiResult" class="ai-result"><p class="ai-result-explanation">{{ aiResult.explanation }}</p><div class="ai-result-actions"><n-button type="primary" :loading="creatingFromAi" @click="createFromAi">按此创建规则</n-button><n-button secondary @click="openFromAi">在编辑器中调整</n-button><n-button quaternary @click="aiResult = null">重新生成</n-button></div></div><div class="ai-assistant-hint">未配置模型？前往 <RouterLink to="/settings">设置 → AI 接入</RouterLink> 配置 OpenAI 兼容服务（OpenAI / DeepSeek / 百炼）或本地 Ollama。</div></section>
<section class="automation-principle"><div><span>WHEN</span><strong>何时触发</strong><small>新资源、关注演员或 cron 计划</small></div><i>→</i><div><span>IF</span><strong>满足条件</strong><small>来源、评分、关键词和字幕</small></div><i>→</i><div><span>THEN</span><strong>如何处理</strong><small>自动、确认或仅通知</small></div></section><n-spin :show="loading"><div v-if="rules.items.length" class="automation-list"><article v-for="rule in rules.items" :key="rule.id"><div class="rule-state"><IconAutomation /><n-switch :value="rule.enabled" @update:value="value=>toggle(rule,value)" /></div><button class="rule-copy" @click="open(rule)"><span><b>{{ rule.mode }}</b>{{ rule.enabled?'运行中':'已停用' }}</span><strong>{{ rule.name }}</strong><p>WHEN {{ rule.triggerType }}{{ rule.triggerType === 'SCHEDULE' && rule.triggerConfig.cron ? ` (${rule.triggerConfig.cron})` : '' }} · IF 评分 ≥ {{ rule.conditions.minScore ?? 0 }} · THEN {{ rule.actionType }}</p><small>{{ rule.lastExplanation || (rule.lastRunAt ? `上次检查 ${formatDate(rule.lastRunAt)}` : '等待第一次检查') }}</small></button><n-button quaternary circle type="error" aria-label="删除规则" @click="remove(rule)"><template #icon><IconTrash /></template></n-button></article><PaginationBar :page="page" :page-size="pageSize" :total="rules.total" @update:page="changePage" @update:page-size="changePageSize" /></div><div v-else class="quiet-empty large"><IconAutomation :size="34" /><strong>没有自动化规则也能完整使用 Luma</strong><span>手动搜索和获取始终可用。需要减少重复操作时，用 AI 助手生成或手动创建第一条规则。</span><n-button type="primary" @click="open()">创建规则</n-button></div></n-spin>
<n-modal v-model:show="showEditor" preset="card" class="automation-editor" :title="editingId?'编辑自动化':'新建自动化'" :bordered="false"><div class="editor-steps"><button v-for="number in 3" :key="number" :class="{active:step===number,done:step>number}" @click="step=number"><span>{{ number }}</span>{{ ['WHEN','IF','THEN'][number-1] }}</button></div><div v-if="step===1" class="editor-pane"><span class="eyebrow">WHEN</span><h2>什么时候开始判断？</h2><n-form-item label="规则名称"><n-input v-model:value="form.name" placeholder="例如：关注演员的新资源" /></n-form-item><n-form-item label="触发器"><n-select v-model:value="form.triggerType" :options="triggers" /></n-form-item><n-form-item v-if="form.triggerType==='SCHEDULE'" label="cron 表达式"><n-input v-model:value="form.cron" placeholder="分 时 日 月 星期，例如 0 20 * * 1（每周一 20:00）" /><small class="cron-hint">按服务器本地时区执行；0 和 7 都表示周日</small></n-form-item></div><div v-else-if="step===2" class="editor-pane"><span class="eyebrow">IF</span><h2>哪些资源符合要求？</h2><div class="form-grid"><n-form-item label="指定来源"><n-input v-model:value="form.providerKey" placeholder="留空表示全部来源" /></n-form-item><n-form-item label="标题关键词"><n-input v-model:value="form.keyword" placeholder="可选" /></n-form-item><n-form-item label="最低推荐评分"><n-input-number v-model:value="form.minScore" :min="0" :max="100" style="width:100%" /></n-form-item><n-form-item label="必须包含字幕"><n-switch v-model:value="form.requireSubtitle" /></n-form-item></div></div><div v-else class="editor-pane"><span class="eyebrow">THEN</span><h2>匹配后如何处理？</h2><n-form-item label="执行方式"><n-select v-model:value="form.mode" :options="modes" /></n-form-item><div class="mode-explanation"><strong>{{ form.mode==='AUTO'?'直接进入获取流程':form.mode==='CONFIRM'?'在“需要关注”中等待确认':'只生成通知' }}</strong><span>自动化不会绕过资源排序、重复保护或获取状态机。</span></div></div><template #footer><div class="modal-footer"><n-button v-if="step>1" @click="step--">上一步</n-button><span /><n-button v-if="step<3" type="primary" @click="step++">下一步</n-button><n-button v-else type="primary" :loading="saving" @click="save">保存规则</n-button></div></template></n-modal></template>
